# Result Analysis Workflow Configuration
name: "result-analysis"
description: "Analyze test results and identify patterns, trends, and quality insights"
author: "Franzy"

config_source: "{project-root}/bmad/qa/config.yaml"
output_folder: "{config_source}:output_folder"
test_results_folder: "{config_source}:test_results_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/bmad/qa/workflows/result-analysis"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

default_output_file: "{test_results_folder}/analysis-{date}.md"
standalone: true
